name: Source Code Check

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_source_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch source code
        run: python .github-scripts/fetch_source_code.py

      - name: Check for changes
        run: python .github-scripts/check_for_changes.py
        env:
          SMTP_SERVER: smtp.rediffmail.com
          SMTP_PORT: 586
          EMAIL_USERNAME: ekanturadescript@rediffmail.com
          EMAIL_PASSWORD: Password@123
          TO_EMAIL: ekant.urade@gmail.com
